"""empty message

Revision ID: 36696e520126
Revises: ad966403b6a1
Create Date: 2025-04-16 08:14:01.693728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36696e520126'
down_revision = 'ad966403b6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
